"""Go 代码生成器。

为每张表、每个端生成:
    {Table}/{Table}Data.go    数据结构(struct + Read 方法)
    {Table}/{Table}Table.go   管理结构(Load([]byte) + Get/TryGet/GetAll)
以及每端共用一次的:
    TableReader.go            纯二进制读取器(吃 []byte)

与 binary_writer.py 的写入严格对应:小端、无字段描述区。
"""
from __future__ import annotations

from typing import List

from .. import schema as S
from ..schema import FieldDef, TableSchema
from .base import OutputFile

# type_code -> Go 类型字符串
_GO_SCALAR = {
    S.T_INT: "int32",
    S.T_FLOAT: "float32",
    S.T_BOOL: "bool",
    S.T_STRING: "string",
}
_GO_ARRAY = {
    S.T_INT_ARRAY: "[]int32",
    S.T_FLOAT_ARRAY: "[]float32",
    S.T_BOOL_ARRAY: "[]bool",
    S.T_STRING_ARRAY: "[]string",
}
# 读取器方法名(按 type_code)
_GO_READER = {
    S.T_INT: "ReadInt32",
    S.T_FLOAT: "ReadFloat32",
    S.T_BOOL: "ReadBool",
    S.T_STRING: "ReadString",
    S.T_INT_ARRAY: "ReadInt32Array",
    S.T_FLOAT_ARRAY: "ReadFloat32Array",
    S.T_BOOL_ARRAY: "ReadBoolArray",
    S.T_STRING_ARRAY: "ReadStringArray",
}


def _go_type(fdef: FieldDef) -> str:
    return _GO_ARRAY[fdef.type_code] if fdef.is_array else _GO_SCALAR[fdef.type_code]


def _go_key_type(fdef: FieldDef) -> str:
    return _GO_SCALAR.get(fdef.type_code, "int32")


def _reader_call(fdef: FieldDef) -> str:
    return f"r.{_GO_READER[fdef.type_code]}()"


def _export_name(name: str) -> str:
    """Go 导出字段需首字母大写。"""
    if not name:
        return "Field"
    return name[0].upper() + name[1:]


# Go 保留字/内置包名,不能用作 package 名(否则编译失败)
_GO_RESERVED_PKG = {
    "break", "case", "chan", "const", "continue", "default", "defer", "else",
    "fallthrough", "for", "func", "go", "goto", "if", "import", "interface",
    "map", "package", "range", "return", "select", "struct", "switch", "type",
    "var",
}


def _safe_go_pkg(name: str) -> str:
    """package 名兜底:命中保留字则加后缀,避免 package go 这种非法写法。"""
    if name in _GO_RESERVED_PKG:
        return name + "_tbl"
    return name


class GoGenerator:
    """绑定包名后的 Go 生成器实例。

    Go 没有"命名空间"概念,这里 self.namespace 实际是 Go 的 package 名。
    """

    name = "go"

    def __init__(self, namespace: str) -> None:
        # Go package 名必须小写、无非法字符;derive_namespace 已做基本 sanitize,
        # 这里额外强制小写以符合 Go 惯例,并兜底保留字
        pkg = (namespace or "gamedata").lower()
        self.namespace = _safe_go_pkg(pkg)

    def generate(
        self,
        schema: TableSchema,
        side: str,
        fields: List[FieldDef],
        subdirs_by_table: bool = False,
    ) -> List[OutputFile]:
        table_cls = schema.name
        data_cls = f"{table_cls}Data"
        prefix = f"{table_cls}/" if subdirs_by_table else ""
        return [
            OutputFile(
                relative_path=f"{prefix}{data_cls}.go",
                content=self._gen_data(schema, fields, side, data_cls),
            ),
            OutputFile(
                relative_path=f"{prefix}{table_cls}Table.go",
                content=self._gen_table(schema, fields, table_cls, data_cls),
            ),
        ]

    def shared_files(self) -> List[OutputFile]:
        return [OutputFile(
            relative_path="TableReader.go",
            content=_render_reader(self.namespace),
            is_shared=True,
        )]

    # ---------------- 模板 ----------------

    def _gen_data(self, schema: TableSchema, fields: List[FieldDef], side: str, data_cls: str) -> str:
        pkg = self.namespace
        field_lines: list[str] = []
        for i, fdef in enumerate(fields):
            gotype = _go_type(fdef)
            fname = _export_name(fdef.name)
            comment = f"\t// {fdef.desc}\n" if fdef.desc else ""
            pk = " // 主键" if i == 0 else ""
            field_lines.append(f"{comment}\t{fname} {gotype}{pk}")
        fields_block = "\n".join(field_lines)

        read_lines = [f"\td.{_export_name(fdef.name)} = {_reader_call(fdef)}" for fdef in fields]
        read_block = "\n".join(read_lines) if read_lines else "\t// 无字段"

        return _DATA_TEMPLATE.format(
            pkg=pkg, data_cls=data_cls, table_name=schema.name,
            file_name=schema.file_name, side=side,
            fields_block=fields_block, read_block=read_block,
        )

    def _gen_table(self, schema: TableSchema, fields: List[FieldDef], table_cls: str, data_cls: str) -> str:
        pkg = self.namespace
        key_field = fields[0]
        key_type = _go_key_type(key_field)
        key_name = _export_name(key_field.name)

        return _TABLE_TEMPLATE.format(
            pkg=pkg, table_cls=table_cls, data_cls=data_cls,
            file_name=schema.file_name, key_type=key_type, key_name=key_name,
        )


# —— 数据类模板 ——
_DATA_TEMPLATE = """// Code generated by TableAssembly. DO NOT EDIT.
// Source: {file_name} [{side}]

package {pkg}

// {data_cls} {table_name}表数据({side})。
type {data_cls} struct {{
{fields_block}
}}

// Read 从二进制读取器读取一条数据。
func (d *{data_cls}) Read(r *TableReader) {{
{read_block}
}}
"""

# —— 管理类模板 ——
_TABLE_TEMPLATE = """// Code generated by TableAssembly. DO NOT EDIT.
// Source: {file_name}

package {pkg}

// {table_cls}Table {table_cls}表管理结构。
// 文件加载由调用方处理(资源系统/包管理...),本结构只接收已读入内存的二进制数据。
type {table_cls}Table struct {{
\tm    map[{key_type}]*{data_cls}
\tlist []*{data_cls}
}}

// Load 从二进制数据加载整张表。
func (t *{table_cls}Table) Load(bytes []byte) error {{
\tr := NewTableReader(bytes)
\tr.CheckMagic("ETBL")      // magic
\tr.ReadInt16()              // version
\trowCount := r.ReadInt32()  // rowCount
\tr.ReadInt16()              // fieldCount(顺序已固化在本文件)

\tt.m = make(map[{key_type}]*{data_cls}, rowCount)
\tt.list = make([]*{data_cls}, 0, rowCount)
\tfor i := 0; i < rowCount; i++ {{
\t\td := &{data_cls}{{}}
\t\td.Read(r)
\t\tt.m[d.{key_name}] = d
\t\tt.list = append(t.list, d)
\t}}
\treturn nil
}}

// Get 按主键取数据,不存在返回 nil。
func (t *{table_cls}Table) Get(id {key_type}) *{data_cls} {{
\treturn t.m[id]
}}

// Count 返回数据条数。
func (t *{table_cls}Table) Count() int {{ return len(t.list) }}

// GetAll 返回全部数据列表。
func (t *{table_cls}Table) GetAll() []*{data_cls} {{ return t.list }}
"""

# —— 共用读取器模板(用 {PKG} 占位避免与 .format 的 {} 冲突) ——
_READER_TEMPLATE = """// Code generated by TableAssembly. DO NOT EDIT.
// 通用二进制表读取器:仅负责解析二进制数据,文件加载由调用方自行处理。
// 与 TableAssembly 导出的 .bytes 严格对应(小端)。

package {pkg_placeholder}

import (
\t"encoding/binary"
\t"math"
)

// TableReader 通用二进制表读取器。
type TableReader struct {{
\tdata []byte
\tpos  int
}}

// NewTableReader 构造一个读取器。
func NewTableReader(data []byte) *TableReader {{
\treturn &TableReader{{data: data, pos: 0}}
}}

// CheckMagic 校验魔数,匹配则跳过;不匹配返回 false(不改变 pos)。
func (r *TableReader) CheckMagic(magic string) bool {{
\tfor i := 0; i < len(magic); i++ {{
\t\tif r.data[r.pos+i] != magic[i] {{
\t\t\treturn false
\t\t}}
\t}}
\tr.pos += len(magic)
\treturn true
}}

// ReadInt16 读取 2 字节小端有符号整数。
func (r *TableReader) ReadInt16() int16 {{
\tv := int16(binary.LittleEndian.Uint16(r.data[r.pos:]))
\tr.pos += 2
\treturn v
}}

// ReadInt32 读取 4 字节小端有符号整数。
func (r *TableReader) ReadInt32() int32 {{
\tv := int32(binary.LittleEndian.Uint32(r.data[r.pos:]))
\tr.pos += 4
\treturn v
}}

// ReadFloat32 读取 4 字节 IEEE754 小端浮点。
func (r *TableReader) ReadFloat32() float32 {{
\tbits := binary.LittleEndian.Uint32(r.data[r.pos:])
\tr.pos += 4
\treturn math.Float32frombits(bits)
}}

// ReadBool 读取 1 字节布尔。
func (r *TableReader) ReadBool() bool {{
\tv := r.data[r.pos] != 0
\tr.pos += 1
\treturn v
}}

// ReadString 读取字符串:2 字节小端长度 + UTF-8 字节。
func (r *TableReader) ReadString() string {{
\tn := int(uint16(binary.LittleEndian.Uint16(r.data[r.pos:])))
\tr.pos += 2
\ts := string(r.data[r.pos : r.pos+n])
\tr.pos += n
\treturn s
}}

// ReadInt32Array 读取 int32 数组:4 字节个数 + 逐元素。
func (r *TableReader) ReadInt32Array() []int32 {{
\tn := int(r.ReadInt32())
\ta := make([]int32, n)
\tfor i := 0; i < n; i++ {{
\t\ta[i] = r.ReadInt32()
\t}}
\treturn a
}}

// ReadFloat32Array 读取 float32 数组。
func (r *TableReader) ReadFloat32Array() []float32 {{
\tn := int(r.ReadInt32())
\ta := make([]float32, n)
\tfor i := 0; i < n; i++ {{
\t\ta[i] = r.ReadFloat32()
\t}}
\treturn a
}}

// ReadBoolArray 读取 bool 数组。
func (r *TableReader) ReadBoolArray() []bool {{
\tn := int(r.ReadInt32())
\ta := make([]bool, n)
\tfor i := 0; i < n; i++ {{
\t\ta[i] = r.ReadBool()
\t}}
\treturn a
}}

// ReadStringArray 读取 string 数组。
func (r *TableReader) ReadStringArray() []string {{
\tn := int(r.ReadInt32())
\ta := make([]string, n)
\tfor i := 0; i < n; i++ {{
\t\ta[i] = r.ReadString()
\t}}
\treturn a
}}
"""


def _render_reader(namespace: str) -> str:
    pkg = _safe_go_pkg((namespace or "gamedata").lower())
    return _READER_TEMPLATE.format(pkg_placeholder=pkg)
